[datastructures]
git-tree-sha1 = "9e3a90a40bc6d729881300de017e7e8bf20dafcc"

    [[datastructures.download]]
    sha256 = "0d4fba02f80e7c5eada63fae0402effbbe2ccbeb4d204c1d826cc85e67a582b0"
    url = "https://github.com/gap-packages/datastructures/releases/download/v0.3.1/datastructures-0.3.1.tar.gz"
