[modulepresentationsforcap]
git-tree-sha1 = "c60bb7b200f614a6ab9b8f826e37e316456131cd"

    [[modulepresentationsforcap.download]]
    sha256 = "d65cf713a0c6159add5b46923a723807de0fc6a0be43b592d652768aee9045d1"
    url = "https://github.com/homalg-project/CAP_project/releases/download/ModulePresentationsForCAP-2022.12-01/ModulePresentationsForCAP-2022.12-01.tar.gz"
