[modulepresentationsforcap]
git-tree-sha1 = "1d19a13b65a366c5d2feaf7e8b39fdcb4fc15639"

    [[modulepresentationsforcap.download]]
    sha256 = "1bdcd2694e771a609f36515989e2b3552220e7d09b49f1041a1e7536870f6352"
    url = "https://github.com/homalg-project/CAP_project/releases/download/ModulePresentationsForCAP-2024.09-02/ModulePresentationsForCAP-2024.09-02.tar.gz"
