[curlinterface]
git-tree-sha1 = "436b9d8a5bad8837a696af648f882b92a3c78d41"

    [[curlinterface.download]]
    sha256 = "bdce5de61d50cd21ecd7c3267e5e9df2b604b99ec8add824a7e64ccc3a907a97"
    url = "https://github.com/gap-packages/curlInterface/releases/download/v2.3.1/curlInterface-2.3.1.tar.gz"
