name = "GAP_pkg_curlinterface"
uuid = "a0d106a5-6018-4a8e-ad12-3d03dae2a9d6"
authors = ["Max Horn <max@quendi.de>"]
version = "2.3.1"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.12"
julia = "1.6"
