[gbnp]
git-tree-sha1 = "2294eab57d72f1f1050feaab502f0bb0e1f7c8bb"

    [[gbnp.download]]
    sha256 = "3dfdc1a2c4fa3a80d704cfeb22398640fecf777760a750aa94f69e7fbcffaa51"
    url = "https://github.com/gap-packages/gbnp/releases/download/v1.0.5/gbnp-1.0.5.tar.gz"
