[normalizinterface]
git-tree-sha1 = "09621864208537f21ff58aabc6f244647cc45b8d"

    [[normalizinterface.download]]
    sha256 = "3a5caa2c77f557a8ef5f18be4c0fc2a97487e4f71ae49b58ec76dab7ac55bd8a"
    url = "https://github.com/gap-packages/NormalizInterface/releases/download/v1.3.5/NormalizInterface-1.3.5.tar.gz"
