[normalizinterface]
git-tree-sha1 = "c1466865fc9533ce67cbcd62f9c51b5b2b01008b"

    [[normalizinterface.download]]
    sha256 = "286700d82a2b5a240ff8474990cecfb22526a80b0f28252a95f4792ccde4cb6b"
    url = "https://github.com/gap-packages/NormalizInterface/releases/download/v1.3.7/NormalizInterface-1.3.7.tar.gz"
