name = "GAP_pkg_normalizinterface"
uuid = "f4fe60da-1063-4d3a-a21e-bc44837402fe"
authors = ["Max Horn <max@quendi.de>"]
version = "1.3.5"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
