[linearalgebraforcap]
git-tree-sha1 = "69c5187dd1c79a0719d5354fcc8aacc0adb13ed5"

    [[linearalgebraforcap.download]]
    sha256 = "0f395f34eccbac810f5207efa38bb00d2daff67ae2075778c0555a1407f986ad"
    url = "https://github.com/homalg-project/CAP_project/releases/download/LinearAlgebraForCAP-2024.10-01/LinearAlgebraForCAP-2024.10-01.tar.gz"
