name = "GAP_pkg_linearalgebraforcap"
uuid = "ad625d54-c89e-4bb7-ac1e-405d3c21b420"
authors = ["Max Horn <max@quendi.de>"]
version = "2022.12.4"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.12"
julia = "1.6"
