[majoranaalgebras]
git-tree-sha1 = "84d3a88de862ab3d43d62809518d9f7a144c7ee8"

    [[majoranaalgebras.download]]
    sha256 = "ee0edc3ee3314958444c0d5daca5ebb9972cd6f4fc540d8b4185932311c63926"
    url = "https://github.com/gap-packages/MajoranaAlgebras/releases/download/v1.5.2/MajoranaAlgebras-1.5.2.tar.gz"
