[majoranaalgebras]
git-tree-sha1 = "7f5d0257536a5b425debb0c8b3663efd267939cb"

    [[majoranaalgebras.download]]
    sha256 = "e13011470f5d2cc887a4b9bb46d3c6aa00bd3a78ebc31774519107cb07ca2219"
    url = "https://github.com/gap-packages/MajoranaAlgebras/releases/download/v1.5.1/MajoranaAlgebras-1.5.1.tar.gz"
