name = "GAP_pkg_majoranaalgebras"
uuid = "38aec7a9-b848-4ea7-9a03-5939cfedc53d"
authors = ["Max Horn <max@quendi.de>"]
version = "1.5.0"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
