name = "GAP_pkg_patternclass"
uuid = "b4f5e156-9cd7-46d7-9ceb-64aeeadb89cb"
authors = ["Max Horn <max@quendi.de>"]
version = "2.4.5"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.12"
julia = "1.6"
