name = "GAP_pkg_toricvarieties"
uuid = "a5e14ca4-61a3-402a-8c48-3200a6ed4dca"
authors = ["Max Horn <max@quendi.de>"]
version = "2022.7.13"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
