name = "GAP_pkg_smallgrp"
uuid = "adeebd5f-8e24-40dc-b8ba-d9d12c9c005f"
authors = ["Max Horn <max@quendi.de>"]
version = "1.5.1"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.12"
julia = "1.6"
