name = "GAP_pkg_smallsemi"
uuid = "fee9c766-ecaf-4fbe-b7ef-8d994cd763cd"
authors = ["Max Horn <max@quendi.de>"]
version = "0.7.1"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.12"
julia = "1.6"
