name = "GAP_pkg_symbcompcc"
uuid = "5485673c-4082-4acd-beed-572e0d9d969f"
authors = ["Max Horn <max@quendi.de>"]
version = "1.3.2"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
