[monoidalcategories]
git-tree-sha1 = "405e003650edaad899c2b4777be50698efd157e2"

    [[monoidalcategories.download]]
    sha256 = "cd78c67ee8c6f73a24e2093d40980c1cd10e14ceb1cee2da01afdb8dfb9a76d7"
    url = "https://github.com/homalg-project/CAP_project/releases/download/MonoidalCategories-2024.09-05/MonoidalCategories-2024.09-05.tar.gz"
