name = "GAP_pkg_monoidalcategories"
uuid = "c99bc466-6381-47e3-aa61-8bf19ac8def2"
authors = ["Max Horn <max@quendi.de>"]
version = "2024.9.5"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.12"
julia = "1.6"
