[standardff]
git-tree-sha1 = "8ab9ba99f16c392e4cf594188da2473dc9967e68"

    [[standardff.download]]
    sha256 = "a4066f06249f73fe864afcb4a448adae99a9bb259b5abb5cbbe16f114d3e44b0"
    url = "https://www.math.rwth-aachen.de/~Frank.Luebeck/gap/StandardFF//StandardFF-0.9.4.tar.gz"
