[standardff]
git-tree-sha1 = "28827b60cbeb2aceb8825eb956aec446d8cf5e12"

    [[standardff.download]]
    sha256 = "7e9ffeb9dbe0ddab862a524b1379c09732ef7b40bea2b04ce01db3fb9c27e28e"
    url = "https://www.math.rwth-aachen.de/~Frank.Luebeck/gap/StandardFF//StandardFF-1.0.tar.gz"
