name = "GAP_pkg_standardff"
uuid = "eeb196ac-28b0-434c-9344-5a84b2c3fa5b"
authors = ["Max Horn <max@quendi.de>"]
version = "0.9.4"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
