name = "GAP_pkg_gradedringforhomalg"
uuid = "39061859-ec86-4ba4-9b3f-fd0b9b9d11c1"
authors = ["Max Horn <max@quendi.de>"]
version = "2024.7.1"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.12"
julia = "1.6"
