[primgrp]
git-tree-sha1 = "f21a1e00bcecbba5daff832e0d7dcd3f7b2b30ed"

    [[primgrp.download]]
    sha256 = "9d6fde0fa4658100f662c364f77c9fd67b1699e9f3dbb60306ed357cc5837cff"
    url = "https://github.com/gap-packages/primgrp/releases/download/v3.4.4/primgrp-3.4.4.tar.gz"
