name = "GAP_pkg_numericalsgps"
uuid = "95ac9331-2ee8-49d5-98ab-a7dd149b60df"
authors = ["Max Horn <max@quendi.de>"]
version = "1.3.1"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
