[repndecomp]
git-tree-sha1 = "e606b387fd5c3560554321b5de205fc9fe7a2ca5"

    [[repndecomp.download]]
    sha256 = "bda2ceadf512ffac17794c0b2c6640c4ea18d5a8929bb9de1cfe73eb5e04bbb2"
    url = "https://github.com/gap-packages/RepnDecomp/releases/download/v1.3.0/RepnDecomp-1.3.0.tar.gz"
