name = "GAP_pkg_repndecomp"
uuid = "6312ce51-f39b-4a19-8af2-c689d7d9b255"
authors = ["Max Horn <max@quendi.de>"]
version = "1.2.1"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
