name = "GAP_pkg_jupyterviz"
uuid = "418ddea0-5d71-49c1-b815-1a27b7fcb6b9"
authors = ["Max Horn <max@quendi.de>"]
version = "1.5.6"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
