[deepthought]
git-tree-sha1 = "5ff15ae74a76bedea14cb529d427e45c4f64faec"

    [[deepthought.download]]
    sha256 = "d07f23ab21f3faa3cd0505e5a042c74226d8efa3d0f6ef9d0b29cd8025f0c775"
    url = "https://github.com/gap-packages/DeepThought/releases/download/v1.0.6/DeepThought-1.0.6.tar.gz"
