name = "GAP_pkg_deepthought"
uuid = "f48a36a4-acd3-4e1f-9c0f-73916dfdff0f"
authors = ["Max Horn <max@quendi.de>"]
version = "1.0.6"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
