[ringsforhomalg]
git-tree-sha1 = "63bf4621f553288a025543761edf07cf7efffeab"

    [[ringsforhomalg.download]]
    sha256 = "acfbbb152b48629988232748e2936e35fa65e5bdccaee21e21b18683ccfd11ca"
    url = "https://github.com/homalg-project/homalg_project/releases/download/RingsForHomalg-2024.11-02/RingsForHomalg-2024.11-02.tar.gz"
