[xmod]
git-tree-sha1 = "7d2e8966c7bd61e54516d7f6fdde3fb948e8df7b"

    [[xmod.download]]
    sha256 = "9fcab572ae9fcbdc7af3355b4d5fc1aa29911e8edd8d50df5d7ad79f42965ccf"
    url = "https://github.com/gap-packages/xmod/releases/download/v2.92/XMod-2.92.tar.gz"
