name = "GAP_pkg_edim"
uuid = "09fd22cd-e33a-4c19-9cda-c7f179d983b1"
authors = ["Max Horn <max@quendi.de>"]
version = "1.3.6"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
