name = "GAP_pkg_gapdoc"
uuid = "1bea19b5-7cd3-441d-ac8b-456b868ba034"
authors = ["Max Horn <max@quendi.de>"]
version = "1.6.6"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
