[caratinterface]
git-tree-sha1 = "13ed4fe718f84009ff04e3bdfcf6ed472254e285"

    [[caratinterface.download]]
    sha256 = "fdbc0f86befd8bf575c93475b33f58329ce99fe2ef97ba69af1478bc8664059c"
    url = "https://www.math.uni-bielefeld.de/~gaehler/gap/CaratInterface/CaratInterface-2.3.7.tar.gz"
