name = "GAP_pkg_grpconst"
uuid = "b99f7a03-7cf6-48f1-9f46-b20e3f32c1c8"
authors = ["Max Horn <max@quendi.de>"]
version = "2.6.3"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
