name = "GAP_pkg_rds"
uuid = "86dac290-62c9-4938-9c0d-e3c4ee6eca8b"
authors = ["Max Horn <max@quendi.de>"]
version = "1.8.0"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
