[example]
git-tree-sha1 = "c4e3d02756d01144f569550fa3bb1c294011c7cd"

    [[example.download]]
    sha256 = "56abe7342b9c1eae77a18adfd43cd51f2eaee1b2988eaeeeadbc9125ca4013c0"
    url = "https://github.com/gap-packages/example/releases/download/v4.4.0/Example-4.4.0.tar.gz"
