name = "GAP_pkg_crime"
uuid = "922f8feb-abcc-459c-91f9-275b6b24f617"
authors = ["Max Horn <max@quendi.de>"]
version = "1.6.0"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
