name = "GAP_pkg_toric"
uuid = "988949cb-e9bc-405e-a224-ab727eb776bd"
authors = ["Max Horn <max@quendi.de>"]
version = "1.9.5"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
