[localizeringforhomalg]
git-tree-sha1 = "b57f2abf1316847574d127a274634c9e863c7ed6"

    [[localizeringforhomalg.download]]
    sha256 = "26a040a56df49f2a4d4b068ae1ae006f5b359379d9575f4a08c002bb1ccf95ad"
    url = "https://github.com/homalg-project/homalg_project/releases/download/LocalizeRingForHomalg-2023.10-01/LocalizeRingForHomalg-2023.10-01.tar.gz"
