name = "GAP_pkg_localizeringforhomalg"
uuid = "4db6610a-1afe-42a0-9ba3-dfcd45e0bef9"
authors = ["Max Horn <max@quendi.de>"]
version = "2022.11.1"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.12"
julia = "1.6"
