name = "GAP_pkg_corelg"
uuid = "24a18caf-bb73-459e-99bb-4f39dddc1c3a"
authors = ["Max Horn <max@quendi.de>"]
version = "1.56.0"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.12"
julia = "1.6"
