name = "GAP_pkg_simpcomp"
uuid = "5f3bb644-8fc9-4ac8-9d3f-d072745dbf6b"
authors = ["Max Horn <max@quendi.de>"]
version = "2.1.14"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
