name = "GAP_pkg_crypting"
uuid = "83efc43a-97b2-41ad-9494-899b3fbce1d7"
authors = ["Max Horn <max@quendi.de>"]
version = "0.10.4"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
