name = "GAP_pkg_mapclass"
uuid = "3bbc57b8-f676-4a1d-b653-a68a77e8a3bd"
authors = ["Max Horn <max@quendi.de>"]
version = "1.4.6"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
