[matricesforhomalg]
git-tree-sha1 = "09aacae2caaa76d10843c9c9e19d0bc851cbd7b8"

    [[matricesforhomalg.download]]
    sha256 = "6c107ff0451efa601e5604859155d411c5505be5c6f472c3e7c7daeb915bac6f"
    url = "https://github.com/homalg-project/homalg_project/releases/download/MatricesForHomalg-2022.12-01/MatricesForHomalg-2022.12-01.tar.gz"
