name = "GAP_pkg_matricesforhomalg"
uuid = "d5a3f448-9dd7-4526-8dce-896e77db8d5d"
authors = ["Max Horn <max@quendi.de>"]
version = "2022.12.1"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
