name = "GAP_pkg_wedderga"
uuid = "d223fca3-ed27-451e-8d5d-3aa77027c51c"
authors = ["Max Horn <max@quendi.de>"]
version = "4.10.2"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
