[gradedmodules]
git-tree-sha1 = "bf849e799e1863f0ad4a5f5d10fab9a681c412d9"

    [[gradedmodules.download]]
    sha256 = "9e6fbe846547dfad519264cdb40a1ffb0b2a8b2a56bc7b1ccf35f002bb50fc1f"
    url = "https://github.com/homalg-project/homalg_project/releases/download/GradedModules-2024.01-01/GradedModules-2024.01-01.tar.gz"
