name = "GAP_pkg_factint"
uuid = "113a7fa3-442e-4d7c-81dd-9175ed5204cc"
authors = ["Max Horn <max@quendi.de>"]
version = "0.1.0"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.7"
julia = "1.6"
