[xmodalg]
git-tree-sha1 = "b715df6da5b840bfd7bfd53e7b39f8460a2b7363"

    [[xmodalg.download]]
    sha256 = "007ea97b88eade9fe0d5ccd59e61051aecd53bee44aa504a7d7ec84e6c5e75e9"
    url = "https://github.com/gap-packages/xmodalg/releases/download/v1.23/XModAlg-1.23.tar.gz"
