[generalizedmorphismsforcap]
git-tree-sha1 = "1ab9d6455c8663c20c1aa01767fea53140961e9e"

    [[generalizedmorphismsforcap.download]]
    sha256 = "417c829631d6ec1c7fe73c059a3ce8e65458f86a1d930207f95f7a8d7c07f93f"
    url = "https://github.com/homalg-project/CAP_project/releases/download/GeneralizedMorphismsForCAP-2022.12-01/GeneralizedMorphismsForCAP-2022.12-01.tar.gz"
