[generalizedmorphismsforcap]
git-tree-sha1 = "2abc76a796ba2cd63eda1f80d2c4ef44974259e2"

    [[generalizedmorphismsforcap.download]]
    sha256 = "c696b939b22105edd13e86abbc88ff20844f32b766eb11e006f541885391a453"
    url = "https://github.com/homalg-project/CAP_project/releases/download/GeneralizedMorphismsForCAP-2024.09-03/GeneralizedMorphismsForCAP-2024.09-03.tar.gz"
