name = "GAP_pkg_autpgrp"
uuid = "e5a66d7e-0ec0-469e-ae64-8ee147ebc987"
authors = ["Max Horn <max@quendi.de>"]
version = "1.11.0"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
