name = "GAP_pkg_uuid"
uuid = "ebb265ac-bebb-4ff5-9f6d-f387af70ced4"
authors = ["Max Horn <max@quendi.de>"]
version = "0.7.0"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
