[lpres]
git-tree-sha1 = "95afad2a750fbc23a09cd580f7b97e8902583a1c"

    [[lpres.download]]
    sha256 = "4dddad0905b2ed77cf7ac15fd0f95fdececc82a1dfeb1ea17d9b7a97dab59740"
    url = "https://github.com/gap-packages/lpres/releases/download/v1.1.1/lpres-1.1.1.tar.gz"
