[recog]
git-tree-sha1 = "499f8e887617001e5270da49ecff3ced1f2bbdad"

    [[recog.download]]
    sha256 = "0b8d8cef7f648c50006014f3f9bd85d4bf6b5f594c9bddbaf87f18532cbaf0ec"
    url = "https://github.com/gap-packages/recog/releases/download/v1.4.2/recog-1.4.2.tar.gz"
