name = "GAP_pkg_cohomolo"
uuid = "af553728-c27c-4a18-9dda-3e7b775e7ca3"
authors = ["Max Horn <max@quendi.de>"]
version = "1.6.10"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GAP = "0.9"
julia = "1.6"
